models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: dim_accounts
    columns:
      - name: account_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_id
      - name: account_type
        tests:
          - accepted_values:
              arguments:
                values: ['SAVINGS', 'CHECKING', 'FIXED_DEPOSIT']

  - name: fact_transactions
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique
      - name: account_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_accounts')
                field: account_id
      - name: transaction_type
        tests:
          - accepted_values:
              arguments:
                values: ['DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'PAYMENT', 'REFUND']
